Increase fty-asset SRR version
42ity/fty-asset pull request #254
Opened 2021-11-09 09:57 UTC by stark-dev

Increase SRR version to prevent restore of new asset types on older versions

Signed-off-by: Mauro Guerrera <mauroguerrera@eaton.com>

2021-11-09 10:00 UTC, etnKlendathu approved these changes

2021-11-09 10:20 UTC, etnKlendathu approved these changes

2021-11-19 09:58 UTC, perrettecl approved these changes

2021-11-23 14:40 UTC, perrettecl requested changes
https://github.com/42ity/fty-asset/blob/master/server/src/asset-server.cc#L989 will create issue as we have to support former version of the file

2021-11-23 15:23 UTC, perrettecl approved these changes

2021-11-23 15:23 UTC, merged